services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookchon-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    networks:
      - bookchon-net

networks:
  bookchon-net:
    external: true
    name: bookchon-net

